### ISSUE TITLE
Brewfile failure for default-folder-x

### ISSUE THREAD

**Issue by aaronbradshaw** [rvalente/dotfiles#4]
**Describe the bug**
Failure on brew install for default-folder-x

**To Reproduce**
brew bundle --file="${HOME}/.Brewfile"

**Expected behavior**
Install with no errors

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX Mojave

**Comment by rvalente** [comment]
Fixed by https://github.com/rvalente/dotfiles/commit/3e85d168be631db5c36245e1f2f0273a1e7836d5#diff-95e400bd03bd7b404542fc351f9939de

**Comment by rvalente** [comment]
I did the update real quick to save you the trouble of signing your commit and re-opening. Thanks for the issue.
